from __future__ import annotations

# SISO-REF-010-2025 (v36) UID 155 — Transmitter-Major Modulation
MAJOR_MOD_NAMES: dict[int, str] = {
    0: "No Statement",
    1: "Amplitude",
    2: "Amplitude and Angle",
    3: "Angle",
    4: "Combination",
    5: "Pulse",
    6: "Unmodulated",
    7: "CPSM",
    8: "SATCOM",
}

# SISO-REF-010-2025 (v36) UID 8 — Platform Domain
DOMAIN_NAMES: dict[int, str] = {
    0: "Other",
    1: "Land",
    2: "Air",
    3: "Surface",
    4: "Subsurface",
    5: "Space",
}

# SISO-REF-010-2025 (v36) UID 29 — Country (full table, 283 entries)
COUNTRY_NAMES: dict[int, str] = {
    0: "Other",
    1: "Afghanistan (AFG)",
    2: "Albania (ALB)",
    3: "Algeria (DZA)",
    4: "American Samoa (ASM)",
    5: "Andorra (AND)",
    6: "Angola (AGO)",
    7: "Anguilla (AIA)",
    8: "Antarctica (ATA)",
    9: "Antigua and Barbuda (ATG)",
    10: "Argentina (ARG)",
    11: "Aruba (ABW)",
    12: "Ashmore and Cartier Islands (Australia)",
    13: "Australia (AUS)",
    14: "Austria (AUT)",
    15: "Bahamas (BHS)",
    16: "Bahrain (BHR)",
    17: "Baker Island (United States)",
    18: "Bangladesh (BGD)",
    19: "Barbados (BRB)",
    20: "Bassas da India (France)",
    21: "Belgium (BEL)",
    22: "Belize (BLZ)",
    23: "Benin (BEN)",
    24: "Bermuda (BMU)",
    25: "Bhutan (BTN)",
    26: "Bolivia (Plurinational State of) (BOL)",
    27: "Botswana (BWA)",
    28: "Bouvet Island (BVT)",
    29: "Brazil (BRA)",
    30: "British Indian Ocean Territory (IOT)",
    31: "Virgin Islands (British) (VGB)",
    32: "Brunei Darussalam (BRN)",
    33: "Bulgaria (BGR)",
    34: "Burkina Faso (BFA)",
    35: "Myanmar (MMR)",
    36: "Burundi (BDI)",
    37: "Cambodia (KHM)",
    38: "Cameroon (CMR)",
    39: "Canada (CAN)",
    40: "Cabo Verde (CPV)",
    41: "Cayman Islands (CYM)",
    42: "Central African Republic (CAF)",
    43: "Chad (TCD)",
    44: "Chile (CHL)",
    45: "China, People's Republic of (CHN)",
    46: "Christmas Island (CXR)",
    47: "Cocos (Keeling) Islands (CCK)",
    48: "Colombia (COL)",
    49: "Comoros (COM)",
    50: "Congo (COG)",
    51: "Cook Islands (COK)",
    52: "Coral Sea Islands (Australia)",
    53: "Costa Rica (CRI)",
    54: "Cuba (CUB)",
    55: "Cyprus (CYP)",
    56: "Czechoslovakia (CSK)",
    57: "Denmark (DNK)",
    58: "Djibouti (DJI)",
    59: "Dominica (DMA)",
    60: "Dominican Republic (DOM)",
    61: "Ecuador (ECU)",
    62: "Egypt (EGY)",
    63: "El Salvador (SLV)",
    64: "Equatorial Guinea (GNQ)",
    65: "Ethiopia (ETH)",
    66: "Europa Island (France)",
    67: "Falkland Islands (Malvinas) (FLK)",
    68: "Faroe Islands (FRO)",
    69: "Fiji (FJI)",
    70: "Finland (FIN)",
    71: "France (FRA)",
    72: "French Guiana (GUF)",
    73: "French Polynesia (PYF)",
    74: "French Southern Territories (ATF)",
    75: "Gabon (GAB)",
    76: "Gambia, The (GMB)",
    77: "Gaza Strip (Israel)",
    78: "Germany (DEU)",
    79: "Ghana (GHA)",
    80: "Gibraltar (GIB)",
    81: "Glorioso Islands (France)",
    82: "Greece (GRC)",
    83: "Greenland (GRL)",
    84: "Grenada (GRD)",
    85: "Guadeloupe (GLP)",
    86: "Guam (GUM)",
    87: "Guatemala (GTM)",
    88: "Guernsey (GGY)",
    89: "Guinea (GIN)",
    90: "Guinea-Bissau (GNB)",
    91: "Guyana (GUY)",
    92: "Haiti (HTI)",
    93: "Heard Island and McDonald Islands (HMD)",
    94: "Honduras (HND)",
    95: "Hong Kong (HKG)",
    96: "Howland Island (United States)",
    97: "Hungary (HUN)",
    98: "Iceland (ISL)",
    99: "India (IND)",
    100: "Indonesia (IDN)",
    101: "Iran (Islamic Republic of) (IRN)",
    102: "Iraq (IRQ)",
    104: "Ireland (IRL)",
    105: "Israel (ISR)",
    106: "Italy (ITA)",
    107: "Cote d'Ivoire (CIV)",
    108: "Jamaica (JAM)",
    109: "Jan Mayen (Norway)",
    110: "Japan (JPN)",
    111: "Jarvis Island (United States)",
    112: "Jersey (JEY)",
    113: "Johnston Atoll (United States)",
    114: "Jordan (JOR)",
    115: "Juan de Nova Island",
    116: "Kenya (KEN)",
    117: "Kingman Reef (United States)",
    118: "Kiribati (KIR)",
    119: "Korea (Democratic People's Republic of) (PRK)",
    120: "Korea (Republic of) (KOR)",
    121: "Kuwait (KWT)",
    122: "Lao People's Democratic Republic (LAO)",
    123: "Lebanon (LBN)",
    124: "Lesotho (LSO)",
    125: "Liberia (LBR)",
    126: "Libya (LBY)",
    127: "Liechtenstein (LIE)",
    128: "Luxembourg (LUX)",
    129: "Madagascar (MDG)",
    130: "Macao (MAC)",
    131: "Malawi (MWI)",
    132: "Malaysia (MYS)",
    133: "Maldives (MDV)",
    134: "Mali (MLI)",
    135: "Malta (MLT)",
    136: "Isle of Man (IMN)",
    137: "Marshall Islands (MHL)",
    138: "Martinique (MTQ)",
    139: "Mauritania (MRT)",
    140: "Mauritius (MUS)",
    141: "Mayotte (MYT)",
    142: "Mexico (MEX)",
    143: "Micronesia (Federated States of) (FSM)",
    144: "Monaco (MCO)",
    145: "Mongolia (MNG)",
    146: "Montserrat (MSR)",
    147: "Morocco (MAR)",
    148: "Mozambique (MOZ)",
    149: "Namibia (NAM)",
    150: "Nauru (NRU)",
    151: "Navassa Island (United States)",
    152: "Nepal (NPL)",
    153: "Netherlands (NLD)",
    154: "Netherlands Antilles (Curacao, Bonaire, Saba, Sint Maarten Sint Eustatius)",
    155: "New Caledonia (NCL)",
    156: "New Zealand (NZL)",
    157: "Nicaragua (NIC)",
    158: "Niger (NER)",
    159: "Nigeria (NGA)",
    160: "Niue (NIU)",
    161: "Norfolk Island (NFK)",
    162: "Northern Mariana Islands (MNP)",
    163: "Norway (NOR)",
    164: "Oman (OMN)",
    165: "Pakistan (PAK)",
    166: "Palmyra Atoll (United States)",
    168: "Panama (PAN)",
    169: "Papua New Guinea (PNG)",
    170: "Paracel Islands (International - Occupied by China, also claimed by Taiwan and Vietnam)",
    171: "Paraguay (PRY)",
    172: "Peru (PER)",
    173: "Philippines (PHL)",
    174: "Pitcairn (PCN)",
    175: "Poland (POL)",
    176: "Portugal (PRT)",
    177: "Puerto Rico (PRI)",
    178: "Qatar (QAT)",
    179: "Reunion (REU)",
    180: "Romania (ROU)",
    181: "Rwanda (RWA)",
    182: "Saint Kitts and Nevis (KNA)",
    183: "Saint Helena, Ascension and Tristan da Cunha (SHN)",
    184: "Saint Lucia (LCA)",
    185: "Saint Pierre and Miquelon (SPM)",
    186: "Saint Vincent and the Grenadines (VCT)",
    187: "San Marino (SMR)",
    188: "Sao Tome and Principe (STP)",
    189: "Saudi Arabia (SAU)",
    190: "Senegal (SEN)",
    191: "Seychelles (SYC)",
    192: "Sierra Leone (SLE)",
    193: "Singapore (SGP)",
    194: "Solomon Islands (SLB)",
    195: "Somalia (SOM)",
    196: "South Georgia and the South Sandwich Islands (SGS)",
    197: "South Africa (ZAF)",
    198: "Spain (ESP)",
    199: "Spratly Islands (International - parts occupied and claimed by China,Malaysia, Philippines, Taiwan, Vietnam)",
    200: "Sri Lanka (LKA)",
    201: "Sudan (SDN)",
    202: "Suriname (SUR)",
    203: "Svalbard (Norway)",
    204: "Eswatini (SWZ)",
    205: "Sweden (SWE)",
    206: "Switzerland (CHE)",
    207: "Syrian Arab Republic (SYR)",
    208: "Taiwan, Province of China (TWN)",
    209: "Tanzania, United Republic of (TZA)",
    210: "Thailand (THA)",
    211: "Togo (TGO)",
    212: "Tokelau (TKL)",
    213: "Tonga (TON)",
    214: "Trinidad and Tobago (TTO)",
    215: "Tromelin Island (France)",
    216: "Palau (PLW)",
    217: "Tunisia (TUN)",
    218: "Turkiye (Republic of) (TUR)",
    219: "Turks and Caicos Islands (TCA)",
    220: "Tuvalu (TUV)",
    221: "Uganda (UGA)",
    222: "Russia (RUS)",
    223: "United Arab Emirates (ARE)",
    224: "United Kingdom of Great Britain and Northern Ireland (GBR)",
    225: "United States of America (USA)",
    226: "Uruguay (URY)",
    227: "Vanuatu (VUT)",
    228: "Holy See (VAT)",
    229: "Venezuela (Bolivarian Republic of) (VEN)",
    230: "Viet Nam (VNM)",
    231: "Virgin Islands (U.S.) (VIR)",
    232: "Wake Island (United States)",
    233: "Wallis and Futuna (WLF)",
    234: "Western Sahara (ESH)",
    235: "West Bank (Israel)",
    236: "Samoa (WSM)",
    237: "Yemen (YEM)",
    240: "Serbia and Montenegro",
    241: "Zaire",
    242: "Zambia (ZMB)",
    243: "Zimbabwe (ZWE)",
    244: "Armenia (ARM)",
    245: "Azerbaijan (AZE)",
    246: "Belarus (BLR)",
    247: "Bosnia and Herzegovina (BIH)",
    248: "Clipperton Island (France)",
    249: "Croatia (HRV)",
    250: "Estonia (EST)",
    251: "Georgia (GEO)",
    252: "Kazakhstan (KAZ)",
    253: "Kyrgyzstan (KGZ)",
    254: "Latvia (LVA)",
    255: "Lithuania (LTU)",
    256: "North Macedonia (MKD)",
    257: "Midway Islands (United States)",
    258: "Moldova (Republic of) (MDA)",
    259: "Montenegro (MNE)",
    260: "Russia",
    261: "Serbia and Montenegro (Montenegro to separate)",
    262: "Slovenia (SVN)",
    263: "Tajikistan (TJK)",
    264: "Turkmenistan (TKM)",
    265: "Ukraine (UKR)",
    266: "Uzbekistan (UZB)",
    267: "Czech Republic (CZE)",
    268: "Slovakia (SVK)",
    269: "Aaland Islands (ALA)",
    270: "Bonaire, Sint Eustatius and Saba (BES)",
    271: "Congo (Democratic Republic of the) (COD)",
    272: "Curacao (CUW)",
    273: "Eritrea (ERI)",
    274: "Saint Barthelemy (BLM)",
    275: "Saint Martin (French Part) (MAF)",
    276: "Serbia (SRB)",
    277: "Sint Maarten (Dutch part) (SXM)",
    278: "South Sudan (SSD)",
    279: "Svalbard and Jan Mayen (SJM)",
    280: "Timor-Leste (TLS)",
    281: "United States Minor Outlying Islands (UMI)",
    282: "Palestine, State of (PSE)",
}

# Reverse lookup: display name → SISO code
COUNTRY_CODES: dict[str, int] = {name: code for code, name in COUNTRY_NAMES.items()}
